services:
  app:
    build: .
    container_name: wallet_api
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:8.4
    container_name: wallet_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${HOST_DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: wallet_nginx
    restart: always
    ports:
      - "${HOST_WEB_PORT:-80}:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - my-network

networks:
  my-network:

volumes:
  db_data: